### ISSUE TITLE
Prepare Text

### ISSUE THREAD

**Issue by miraydamartinez** [spongecoda/pwp-capstones#1]
Your prepare text works great! You could also try the 'join' built-in feature for Python and do the following:
    
    lower_text     = text.lower()
    punctuation    = ".,!?"
    no_punctuation = ''.join(letter for letter in lower_text if letter not in punctuation)
    return no_punctuation.split()

This will essentially remove all the punctuation (specified from the punctuation variable) from the text but keep the text itself in tact (i.e. all the words!)

**Comment by spongecoda** [comment]
Hi Mirayda,
'join' in combination with an iteration + conditional statement is a very nice feature!
Thanks for that hint, i'll use it at the next opportunity!
