### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by miraydamartinez** [spongecoda/pwp-capstones#2]
### Criteria 1: Valid Python Code
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Code included runs without any errors.
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ All of the functions required by this project are correctly and cleanly implemented and they are called in the appropriate order. 
 
### Criteria 3: Software Architecture
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Code is separated into distinct classes and functions each which are invoked for their own purposes. 
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 3 (Meets Expectations)
* _Comment(s):_ Python language features are usually used, but there are 1-3 cases of a coded construction could have been accomplished by a Python builtin. See Issue #1. 

### Criteria 5: Produces Accurate Output
* _Score Level:_ 3 (Meets Expectations)
* _Comment(s):_ All of your code looks good but for some reason the output wouldn't print; I suggest going back and trying to resolve this error.
 
### Overall Score: 18/20
Overall, well done! Your code is nicely formatted which makes grading it an easier process. All of your code does exactly what it is supposed to do and you use a lot of Python built-in features which is great. It shows a deep understanding of the Python programming language!

**Comment by spongecoda** [comment]
Hi Mirayda,
thanks a lot for this positive feedback!
According to Criteria 5:
I guess you mean the missing print statements at "Creating our TextSample Instances (...) Print out each one after instantiating them." ?

# 
# Creating our TextSample Instances 
murderer_sample = TextSample(murder_note, "unknown")
lily_sample = TextSample(lily_trebuchet_intro, "Lily Trebuchet")
myrtle_sample = TextSample(myrtle_beech_intro, "Myrtle Beech")
gregg_sample = TextSample(gregg_t_fishy_intro, "Gregg T Fishy")

# Print out each one after instantiating them
# The following print statements were missing
print(murderer_sample)
print(lily_sample)
print(myrtle_sample)
print(gregg_sample)
# 

All other cells with print statements seem to produce output.

Should i upload a new file?

Thanks and regards!
Malte
